### ISSUE TITLE
how does the Validate Origin Authorization Filter get's setup up?

### ISSUE THREAD

**Issue by maxmedina05** [DaniJG/AntiforgeryExample#1]
how does the Validate Origin Authorization Filter get's setup up?
or where do you configure it?
so the options.Value.WhitelistedOrigins gets a value different from null.
in the ValidateOriginAuthorizationFilter.cs file

**Comment by DaniJG** [comment]
You add them using the standard [Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration) and [Options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options) features of the ASP.NET Core framework.

Basically in appsettings.json or any other configuration source you define the actual values. 
```
{
  "Logging": {
    ...
  },

  "WhitelistedOrigins": ["localhost"]
}
```

Then in your Startup class you wire the `ValidateOriginOptions` to your configuration
```
services.Configure<ValidateOriginOptions>(Configuration);
```

You also need to add the `ValidateOriginAuthorizationFilter` filter to the MVC pipeline
```
services.AddMvc(opts =>
{
     opts.Filters.AddService(typeof(AngularAntiforgeryCookieResultFilter));
     opts.Filters.AddService(typeof(ValidateOriginAuthorizationFilter));
});
```

Now on every request the filter gets executed, and the `ValidateOriginOptions` options are injected. The option values will have been set from the configuration sources like json files, env variables, etc.

**Comment by maxmedina05** [comment]
Thank you so much

**Comment by DaniJG** [comment]
No bother, closing the issue!

**Comment by maxmedina05** [comment]
I'm just struggling now trying to adapt that configuration to the new
asp.net core 2.0 I can't get the configuration there using an
app.config.xml file.
